### PR TITLE
Feature: modulo operator

### PR DESCRIPTION
**Pull request by vektor8891**
Issues:
- #7: adding modulo function.

### CODE REVIEW

**Review by maxinteger — CHANGES_REQUESTED** [review]
Looks very good. 
Only one thing missing. You have to add the new function to the index export.
So please change the `src-index.ts` line 9 to this:
```
import { default as numFn, parseNumber, plNumber } from './data/number/numberFn'
```

then add to the `runtime` object in the same file, line 57, for example:
```
  ...math,
  ...numFn,
  ...fractionNumberFn,
```

**Comment by vektor8891** [comment]
@maxinteger i've added the function to the index export. can you pls have a look?

**Comment by maxinteger** [comment]
@vektor8891 Looks like you reverted all the code changes and the PR contains nothing please check it again

**Comment by vektor8891** [comment]
@maxinteger i created a different branch and open a new PR #13.

**Pull request closed without merging**
